import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={inter.className}>
        <div className='flex  mt-5 flex-col px-2 mx-5 md:w-[50%] md:mx-auto  shadow-lg p-2 rounded-lg bg-slate-100'>

        <Navbar/>
        
        {children}
        </div>
       </body> 
    </html>
  )
}
